[btc]
ip = "192.168.0.185"
port = 8334
rpcusername = "sjyy"
rpcpassword = "Sjyy2018"

[usdt]
ip = "192.168.0.185"
port = 8334
rpcusername = "sjyy"
rpcpassword = "Sjyy2018"

[mysql]
host = "127.0.0.1"
port = 3306
username =  "root"
password = "123456"
dbname = "test"

[validations]
email = "^([a-zA-Z0-9_-])+@([a-zA-Z0-9_-])+(.[a-zA-Z0-9_-])+"
phone = "^(13[0-9]|14[57]|15[0-35-9]|18[07-9])\\d{8}$"


